extends:
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
globals:
  __webpack_public_path__: true
  localStorage: false
  IS_EE: false
settings:
  import/resolver:
    - node:
        - extensions:
            - ".ts"
            - ".tsx"
        - moduleDirectory:
            - node_modules
            - src
plugins:
  - "@typescript-eslint"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: 6
  sourceType: module
  allowImportExportEverywhere: true
  project: ./tsconfig.json
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/ban-ts-comment': off
  no-dupe-args: error
  no-dupe-keys: error
  no-empty: error
  no-extra-semi: error
  no-irregular-whitespace: error
  no-unreachable: error
  consistent-return: error
  curly: error
  default-case: error
  eqeqeq:
    - error
    - always
  no-alert: error
  no-eval: error
  no-multi-spaces: error
  no-sequences: error
  no-unused-expressions: error
  no-useless-return: error
  no-with: error
  radix: error
  import/no-commonjs: error
  no-underscore-dangle: off
  import/no-unresolved: off
  no-else-return:
    - error
    - allowElseIf: true
  lines-between-class-members: off
  promise/always-return: off
  promise/no-callback-in-promise: off
  import/no-named-as-default: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
        - unknown
      pathGroups:
        - pattern: (runtimeEnv|store|router)
          group: external
        - pattern: modules/**
          group: internal
        - pattern: shared/**
          group: internal
        - pattern: utils/**
          group: internal
        - pattern: http/**!(dto)
          group: internal
        - pattern: http/dto/**
          group: internal
        - pattern: ui/**/!(*.tsx)
          group: internal
        - pattern: ui/**/*.tsx
          group: internal
      alphabetize:
        order: asc
        caseInsensitive: false
      newlines-between: always
overrides:
  - files:
      - '*.config.js'
      - '*.config.*.js'
    rules:
      import/no-extraneous-dependencies: off
      import/no-commonjs: off
      import/no-nodejs-modules: off
      filenames/match-regex: off
      no-console: off
