version: "3.6"

services:
    psql:
        container_name: psql
        restart: always
        image: postgres:13.3
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
        env_file:
            ./.env
        volumes:
            - ./docker/postgresql/shared:/var/lib/postgresql
        ports:
            - "5477:5432"
        networks:
            - postgres
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.7
        env_file:
            ./.env
        volumes:
            - ./docker/pgadmin/shared:/var/lib/pgadmin
        ports:
            - "5050:5050"
        restart: unless-stopped
        depends_on:
            - psql
        networks:
            - postgres
    frontend:
        container_name: frontend
        build:
            context: ./
            dockerfile: ./docker/frontend/Dockerfile
        env_file:
            ./.env
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        depends_on:
            - psql
        networks:
            - postgres

    nginx:
        container_name: nginx_friends
        restart: always
        image: nginx
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs
            - ./docker/nginx/core:/etc/nginx/conf.d
            - ./docker/nginx/logs/:/var/log/nginx/
        depends_on:
            - psql
        ports:
            - "443:443"
        networks:
            - postgres

volumes:
    pgadmin-data:

networks:
    postgres:
        driver: bridge
