version: "3.3"

services:
    my-app:
        build:
            context: .
        depends_on:
            - psql
        env_file:
            ./.env
        ports:
            - "5000:5000"
        restart: always
        networks:
            - postgres
    psql:
        container_name: psql
        restart: always
        image: postgres:13.3
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
        env_file:
            ./.env
        volumes:
            - ./docker/postgresql:/var/lib/postgresql
            # Если у вас есть схема БД, которую можно подгрузить на старте, — передайте её
            - ./docker/postgresql-init/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
        ports:
            - "5432:5432"
        networks:
            - postgres
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.7
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
        volumes:
            - ./docker/pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
        depends_on:
            - psql
        networks:
            - postgres
    node:
        container_name: node
        image: node:14.17.6
        restart: always
        volumes:
            - ./node/:/node/
        depends_on:
            - psql
        links:
            - psql

networks:
    postgres:
        driver: bridge
