name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login in docker hub on Yandex Cloud
      run: |
        docker login \
        --username json_key \
        --password-stdin ${{ secrets.JSON_KEY }} \
        cr.yandex
