name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ../private.key
        sudo chmod 600 ../private.key
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
    - run: ssh -i ${{ github.workspace }}/../private.key ${{ secrets.YA_CLOUD_HOST }}
    - run: node -v
#     - run: git --help
#     - run: git clone https://github.com/YaFriends/ya-game-frontend.git .
    - run: cd /home/
    - name: create .env file
      run: echo ${{ secrets.ENV }} > env.txt
    - run: ls
#     - run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
#     - run: |
#         echo 'source /home/runner/yandex-cloud/completion.zsh.inc' >>  ~/.zshrc
#         source "/home/runner/.bashrc"
#         exec -l $SHELL
#     - run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
#     - run: source "/home/runner/.bashrc"
#     - run: exec -l $SHELL
#     - run: yc --help
# 
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - name: create .env file
#       run: echo ${{ secrets.ENV }} > .env
#     - name: create docker image
#       run: yarn && yarn docker:build
#     - name: check docker image
#       run: docker image list
#     - name: login in docker hub on Yandex Cloud
#       run: |
#         echo ${{ secrets.OAUTH_TOKEN_ON_YANDEX_CLOUD }} | docker login \
#           --username oauth \
#           --password-stdin \
#           cr.yandex
#     - name: push frontend
#       run: |
#         docker tag ya-game-frontend_frontend \
#         cr.yandex/${{ secrets.ID_FRONTEND_REGISTRY }}/ya-game-frontend_frontend:latest
#         docker push cr.yandex/${{ secrets.ID_FRONTEND_REGISTRY }}/ya-game-frontend_frontend:latest
#     - name: push backend
#       run: docker image push cr.yandex/${{ secrets.ID_BACNEND_REGISTRY }}/ya-game-frontend_backend:latest
#     - name: push postgres
#       run: docker image push cr.yandex/${{ secrets.ID_DB_REGISTRY }}/postgres:13.3
#     - name: push dpage/pgadmin4
#       run: docker image push cr.yandex/${{ secrets.ID_DB_ADMIN_REGISTRY }}/dpage/pgadmin4:5.7 
        
