name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login in docker hub on Yandex Cloud
      run: |
        docker login \
         --username oauth \
         --password ${{ secrets.OAUTH_TOKEN_ON_YANDEX_CLOUD }} \
         cr.yandex
    - name: check list
      run: docker image list
