name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: create .env file
      run: |
        echo ${{ secrets.ENV }} > .env
    #/home/runner/work/ya-game-frontend/ya-game-frontend/
    - name: create docker image
      run: |
        yarn
        yarn docker:build
    - name: login in docker hub on Yandex Cloud
      run: |
        docker login \
         --username oauth \
         --password ${{ secrets.OAUTH_TOKEN_ON_YANDEX_CLOUD }} \
         cr.yandex
    - name: check list
      run: |
        docker image list
        docker image get 8a4a01e26103
